name: Build and deploy Python app to Azure Web App - sketchify-backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv backend/sketchifybackend/venv
          source backend/sketchifybackend/venv/bin/activate

      - name: Install dependencies
        run: |
          source backend/sketchifybackend/venv/bin/activate
          pip install -r backend/sketchifybackend/requirements.txt

      - name: List directories for verification
        run: |
          ls -la backend/sketchifybackend

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: |
          cd backend/sketchifybackend
          zip -r ../../release.zip ./
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d .

      - name: 'Log in to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'sketchify-backend'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_c3b5ebae805a41eeb9800b3a60a977d0 }}

      - name: Verify installed packages and virtual environment
        run: |
          source backend/sketchifybackend/venv/bin/activate
          pip list
          which daphne
